# Generated by Django 5.0.6 on 2024-05-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_venue_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Approved'),
        ),
    ]
