[dependencies]
python = "3.12.2"
postgresql = "*"
gcc = "*"

[install]
command = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[start]
command = "gunicorn config.wsgi"
